# add eureka configuration
eureka:
  instance:
    hostname: localhost #because we have given localhost to Discovery project
  client: #A Eureka client (your microservice student) needs to register itself with the Eureka Server to be discoverable by other services.
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: students
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_microservice?characterEncoding=UTF-8
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: create
